### ISSUE TITLE
Erreur quand je tente de me login

### ISSUE THREAD

**Issue by jerem-ma** [noctuelles/42-ft_transcendance#34]
Comment ça a pété ?
- `docker compose down -v`
- `docker compose up --build -d`
- Je vais sur `localhost:8080`
- Je clique sur le portail
- Bam, ça pète
![image](https://user-images.githubusercontent.com/59874848/213730066-e2a9042d-302c-4b0f-bd22-a36af2c5b5f1.png)

**Comment by jerem-ma** [comment]
Erreur côté back : 
```
User jmaia finished auth process
[Nest] 30  - 01/20/2023, 3:05:36 PM   ERROR [ExceptionsHandler] 
Invalid `this.prismaService.user.findUnique()` invocation in
/usr/src/app/src/modules/users/users.service.ts:20:46

  17 constructor(private readonly prismaService: PrismaService) {}
  18 
  19 async isUserWithLogin(login: string) {
→ 20 	const user = await this.prismaService.user.findUnique(
The column `User.profileId` does not exist in the current database.
Error: 
Invalid `this.prismaService.user.findUnique()` invocation in
/usr/src/app/src/modules/users/users.service.ts:20:46

  17 constructor(private readonly prismaService: PrismaService) {}
  18 
  19 async isUserWithLogin(login: string) {
→ 20 	const user = await this.prismaService.user.findUnique(
The column `User.profileId` does not exist in the current database.
    at RequestHandler.handleRequestError (/usr/src/app/node_modules/@prisma/client/runtime/index.js:35024:13)
    at RequestHandler.handleAndLogRequestError (/usr/src/app/node_modules/@prisma/client/runtime/index.js:34996:12)
    at RequestHandler.request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:34991:12)
    at PrismaService._request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:36082:16)
    at UsersService.isUserWithLogin (/usr/src/app/src/modules/users/users.service.ts:20:16)
    at AuthService.connectUser (/usr/src/app/src/modules/auth/auth.service.ts:30:9)
    at AuthController.callback (/usr/src/app/src/modules/auth/auth.controller.ts:52:10)
    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

**Comment by jerem-ma** [comment]
C'est la DB qu'était plus à jour du coup
